import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import { cookies } from "next/headers";
import { THEME_1, THEME_2, THEME_3 } from "@/utilities/THEME_COLORS";
import "./globals.css";
import Calculator from "./page";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["300", "500", "600"],
});

export const metadata: Metadata = {
  title: "A simple calculator",
  description: "Generated by Nextjs",
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const getCookiesValue = cookies().get("theme")?.value || "1";
  const cookiesTheme =
    getCookiesValue === "1"
      ? THEME_1
      : getCookiesValue === "2"
      ? THEME_2
      : THEME_3;
  return (
    <html data-colors-theme="Theme-1" lang="en" style={cookiesTheme}>
      <body
        className={`flex justify-center items-center px-6 py-8 bg-[var(--background-theme)] ${leagueSpartan.className} xl:py-24`}
      >
        {/* <ThemeToggle initialTheme={getCookiesValue} /> */}
        <Calculator initialTheme={getCookiesValue} />
      </body>
    </html>
  );
}

export default RootLayout;
